### ISSUE TITLE
Slack Webhook not working

### ISSUE THREAD

**Issue by ofostier** [higanworks/rundeck-slack-incoming-webhook-plugin#38]
Hi all,

I 've installed slack plugin on my Rundeck  build | 2.10.8-1 server.
Slack option correctly appear under Notification part.
I set my slack webhook URL for success and all other possibilities 
But i never receive alert on Slack.

It work when i put a simple cURL to my slack webhook url in a command script.. 

I 've only put the JAR plugin in the right directory
i don't set template or global webhook URL in the project config file.

Any idea ?

**Comment by sawanoboly** [comment]
Is the error log displayed?

**Comment by ofostier** [comment]
No log appear
How can i activate it ?

**Comment by ckaiser79** [comment]
Hello, 

I faced a similar problem. Here are the details: Rundeck 3.0.6-20180917 is used. Maybe it is not compatible, then I did not read it. I configured my job like this:

![grafik](https://user-images.githubusercontent.com/11504021/46631144-d9fa2a00-cb46-11e8-89dd-b249778dccdc.png).

The ``http`` scheme is just to be able to read the payload with tcpdump. Here is the output of tcpdump:

![grafik](https://user-images.githubusercontent.com/11504021/46631281-42e1a200-cb47-11e8-897a-e2528e4e735b.png)

If I use the correct url (with https) I get a http 400 status, which is explainable, since as I read slack expect a json payload and not XML.

I tried to not enable the webhook url, but then nothing is sent. Help is appreciated.

Thanks
Christian

**Comment by NapoSky** [comment]
@ckaiser79 : 
I have exactly the same problem as you with slack 0.8 and Rundeck 3.0.7 which i'm currently deploying.
On another environment I use Rundeck in 2.11.3 with Slack 0.6 and it works.

I just tried to use slack 0.6 on Rundeck 3.0.7, and actually... It works too.
It's probably a bad fix for now, but for a simple usage it does the coffee.

**Comment by sawanoboly** [comment]
Perhaps the compatibility may be lost with this change...
https://github.com/higanworks/rundeck-slack-incoming-webhook-plugin/pull/36

@unicolet If you have time to check this problem, is it possible to fix it?

**Comment by unicolet** [comment]
@sawanoboly I'll try and give it a look asap. Can you assign me so I don't forget? Thanks :-)

**Comment by unicolet** [comment]
@sawanoboly any chance you could label this issue hacktoberfest? (https://hacktoberfest.digitalocean.com/) 😉

**Comment by sawanoboly** [comment]
@unicolet Thanks!

>  Can you assign me so I don't forget? Thanks :-)

May I invite you as a collaborator in this repository if you don't mind?

**Comment by unicolet** [comment]
@sawanoboly sure :-)

**Comment by unicolet** [comment]
Did a quick investigation on rundeck `3.0.7` and I can reproduce the issue. I will post a fix asap :-)

**Comment by unicolet** [comment]
@ofostier did you configure the `webhook_url` at the project or rundeck level?

Since it is required to be specified there and (optionally) overridden in the job the notification will not fire if it's not set in the project properties.
You should find this in `service.log`:

```
Notification: configuration was not valid for plugin 'SlackNotification': webhook_url: required
```

To resolve just add:

```
project.plugin.Notification.SlackNotification.webhook_url=https\://hooks.slack.com/services/*****************
```

then it should work (unless you bump into #37 for which there's an incoming fix and a workaround exists). Let us know how it goes and thanks for your patience :-)

**Comment by ofostier** [comment]
Thx a lot !! It work now.

It should be mentioned in the documentation or by add form in project configuration link in the menu.

By the way. You save me

**Comment by unicolet** [comment]
> by add form in project configuration link in the menu

afaik it should be there 😊

**Comment by unicolet** [comment]
@sawanoboly I'm going to send another PR with README changes, hopefully this weekend :-)

**Comment by sawanoboly** [comment]
This problem has probably been fixed. Please build with the latest code or try using the release version below.

https://github.com/higanworks/rundeck-slack-incoming-webhook-plugin/releases/tag/v0.9.dev
